export const VIDEOS = [
    {
        "rowId": 3,
        "title": "Tripeptide Hair Density Serum",
        "item_id": "m9tjxkkl8dnjf053v",
        "category": "none",
        "username": "@by.loren",
        "video_url": null,
        "review_url": "https://cdn.shopify.com/videos/c/o/v/a9a3485723494dc9aae13c936781c5ec.mp4",
        "enabled_all": true,
        "enabled_body": false,
        "enabled_hair": true,
        "enabled_item": true,
        "enabled_skin": false,
        "product_link": "tripeptide-hair-density-serum",
        "enabled_tanspf": false
    },
    {
        "rowId": 6,
        "title": "Like A Virgin Hair Masque",
        "item_id": "m9tjz7x1xfs0hpnii",
        "category": "none",
        "username": "@hagdaprata_",
        "video_url": null,
        "review_url": "https://cdn.shopify.com/videos/c/o/v/57c3e426e86a4d499e50a0cfe8da171f.mp4",
        "enabled_all": false,
        "enabled_body": false,
        "enabled_hair": true,
        "enabled_item": true,
        "enabled_skin": false,
        "product_link": "super-nourishing-coconut-fig-hair-masque",
        "enabled_tanspf": false
    },
    {
        "rowId": 8,
        "title": "Hair Repairing Leave-in Treatment",
        "item_id": "m9tk2nl0v35tzzvuz",
        "category": "none",
        "username": "@kaelatavares_",
        "video_url": null,
        "review_url": "https://cdn.shopify.com/videos/c/o/v/dd0a89bff95740bfa6825bb6a15bdb84.mp4",
        "enabled_all": true,
        "enabled_body": false,
        "enabled_hair": true,
        "enabled_item": true,
        "enabled_skin": false,
        "product_link": "hair-repairing-leave-in-treatment",
        "enabled_tanspf": true
    },
    {
        "rowId": 3,
        "title": "Tripeptide Hair Density Serum",
        "item_id": "m9tjxkkl8dnjf053v",
        "category": "none",
        "username": "@by.loren",
        "video_url": null,
        "review_url": "https://cdn.shopify.com/videos/c/o/v/a9a3485723494dc9aae13c936781c5ec.mp4#t=5",
        "enabled_all": true,
        "enabled_body": false,
        "enabled_hair": true,
        "enabled_item": true,
        "enabled_skin": false,
        "product_link": "tripeptide-hair-density-serum",
        "enabled_tanspf": false
    },
    {
        "rowId": 6,
        "title": "Like A Virgin Hair Masque",
        "item_id": "m9tjz7x1xfs0hpnii",
        "category": "none",
        "username": "@hagdaprata_",
        "video_url": null,
        "review_url": "https://cdn.shopify.com/videos/c/o/v/57c3e426e86a4d499e50a0cfe8da171f.mp4#t=5",
        "enabled_all": false,
        "enabled_body": false,
        "enabled_hair": true,
        "enabled_item": true,
        "enabled_skin": false,
        "product_link": "super-nourishing-coconut-fig-hair-masque",
        "enabled_tanspf": false
    },
    {
        "rowId": 8,
        "title": "Hair Repairing Leave-in Treatment",
        "item_id": "m9tk2nl0v35tzzvuz",
        "category": "none",
        "username": "@kaelatavares_",
        "video_url": null,
        "review_url": "https://cdn.shopify.com/videos/c/o/v/dd0a89bff95740bfa6825bb6a15bdb84.mp4#t=5",
        "enabled_all": true,
        "enabled_body": false,
        "enabled_hair": true,
        "enabled_item": true,
        "enabled_skin": false,
        "product_link": "hair-repairing-leave-in-treatment",
        "enabled_tanspf": true
    }
]